#cloud-config

package_update: false
package_upgrade: false

packages:
  - wget
  - unzip
  - docker.io

runcmd:
  - /opt/init/install-nomad.sh

users:
  - default

write_files:
  - path: /opt/init/install-nomad.sh
    permissions: "0o755"
    content: |
      cd /opt/init
      wget -O nomad.zip https://releases.hashicorp.com/nomad/1.9.6/nomad_1.9.6_linux_amd64.zip
      mkdir -p nomad
      unzip -d nomad/ nomad.zip
      cp nomad/nomad /usr/local/bin/nomad
      chmod +x /usr/local/bin/nomad
      chown root:root /usr/local/bin/nomad
      mkdir -p /opt/nomad
      chown --recursive root:root /opt/nomad
      systemctl daemon-reload
      systemctl enable nomad
      systemctl start nomad

  - path: /etc/nomad.d/nomad.hcl
    defer: true
    owner: root:root
    permissions: '0o644'
    encoding: b64
    content: "${nomad_config}"
  
  - path: /etc/nomad.d/client.hcl
    defer: true
    owner: root:root
    permissions: "0o644"
    encoding: b64
    content: "${client_config}"

  - path: /etc/systemd/system/nomad.service
    defer: true
    permissions: "0o644"
    encoding: b64
    content: "${systemd_service}"