#cloud-config

package_update: false
package_upgrade: false

packages:
  - wget
  - unzip

# runcmd:
#   - /opt/init/install-consul.sh

users:
  - default
  - name: consul
    system: true
    homedir: "/etc/consul.d"
    shell: /bin/false

write_files:
  - path: /opt/init/install-consul.sh
    permissions: "0o755"
    content: |
      wget -O consul.zip https://releases.hashicorp.com/consul/1.20.4/consul_1.20.4_linux_amd64.zip
      mkdir -p /opt/init/consul
      unzip /opt/init/consul.zip /opt/init/consul/
      cp /opt/init/consul/consul /usr/local/bin/consul
      chmod +x /usr/bin/consul
      chown root:root /usr/bin/consul
      mkdir -p /opt/consul
      chown --recursive consul:consul /opt/consul
      systemctl daemon-reload
      systemctl enable consul
      systemctl start consul

  - path: /etc/consul.d/consul.hcl
    defer: true
    owner: consul:consul
    permissions: "0o644"
    encoding: b64
    content: "${consul_config}"

  - path: /etc/consul.d/server.hcl
    defer: true
    owner: consul:consul
    permissions: "0o644"
    encoding: b64
    content: "${server_config}"

  - path: /etc/systemd/system/consul.service
    defer: true
    permissions: "0o644"
    encoding: b64
    content: "${systemd_service}"
